事業をエンジニアリングしよう ②実装
nakata59/mokumoku pull request #2
Opened 2023-04-18 07:34 UTC by nakata59

【概要】
「事業をエンジニアリングしよう ②実装」の課題を提出いたします。
スクリーンショットの通りテストをパスすることは確認済みです。

【選択した事業課題】
  サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

【実装方針】
- [x] ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
- [x]  イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
- [x]  ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
- [x]  女性限定イベントには女性のみが参加できる。
- [x]  女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
- [x]  女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。

【注意点】
- [x] イベントが女性限定であるかを判定するカラムは"only_woman"とする
- [x]  ユーザーの性別登録のカラムは"gender"とする
- [x]  ユーザー登録時の性別のセレクト部分はenumを使って「その他・男性・女性」が表示される（その際に特に操作が無かれば"その他"が選択される）

【テスト結果】
<img width="503" alt="スクリーンショット 2023-04-18 16 19 23" src="https://user-images.githubusercontent.com/112907406/232704047-6a517746-23ad-40fa-8b83-a0be49306040.png">

2023-04-18 11:05 UTC, takyyk reviewed
いくつか同様の指摘はskipしてしまっているものもあるので全体的に指摘を踏まえて見直してみてください！

2023-04-18 11:05 UTC, takyyk commented on .DS_Store
不要な差分ですね。

2023-04-18 11:05 UTC, takyyk commented on app/views/.DS_Store
不要な差分ですね。

2023-04-18 11:05 UTC, takyyk commented on app/views/events/_event.html.erb
> +      <% if event.only_woman == 1 %>
1がマジックナンバーになってしまっています。モデルにメソッドを作り、ロジックを寄せてみてください。

2023-04-18 11:05 UTC, takyyk commented on app/views/events/_form.html.erb
> +  <% if current_user.gender == "woman" %>
こちらも同様にモデルにロジックを寄せることができそうです。

2023-04-18 11:05 UTC, takyyk commented on app/views/events/show.html.erb
> +                  <% if @event.only_woman.eql?(1) and current_user.gender != "woman"  %>
ここもモデルに作成したロジックを使用してもう少しシンプルに書けそうです。

2023-04-18 11:05 UTC, takyyk commented on db/schema.rb
> +    t.integer "only_woman"
null制約があるとより良いです。

2023-04-18 11:05 UTC, takyyk commented on db/schema.rb
> +    t.integer "gender"
ここも同様にnull制約があるとより良いです。

2023-05-10 11:53 UTC, nakata59 commented on .DS_Store
e49a660b86c0d316ebaa36c626e9a3b71df34501
プルリクエスト対象から除外しました。

2023-05-10 11:53 UTC, nakata59 commented on app/views/.DS_Store
https://github.com/nakata59/mokumoku/pull/2
プルリクエスト対象から除外しました。

2023-05-10 11:55 UTC, nakata59 commented on db/schema.rb
> +    t.integer "only_woman"
e49a660b86c0d316ebaa36c626e9a3b71df34501
null制約とデフォルト0の設定を追加しました。

2023-05-10 11:56 UTC, nakata59 commented on db/schema.rb
> +    t.integer "gender"
e49a660b86c0d316ebaa36c626e9a3b71df34501
null制約とデフォルト0の設定を追加しました。

2023-05-10 11:58 UTC, nakata59 commented on app/views/events/_event.html.erb
> +      <% if event.only_woman == 1 %>
e49a660b86c0d316ebaa36c626e9a3b71df34501
event.rbに女性限定のイベントか判定するメソッドを追加し、
view内のマジックナンバーを解消しました。

2023-05-10 12:01 UTC, nakata59 commented on app/views/events/_form.html.erb
> +  <% if current_user.gender == "woman" %>
e49a660b86c0d316ebaa36c626e9a3b71df34501
user.rbにユーザーが女性か判定するメソッド「woman?」を作成し、
events/_form.html.erbではそのメソッドを使用して対象ユーザーが女性か判定するように記載しました。

2023-05-10 12:03 UTC, nakata59 commented on app/views/events/show.html.erb
> +                  <% if @event.only_woman.eql?(1) and current_user.gender != "woman"  %>
e49a660b86c0d316ebaa36c626e9a3b71df34501
user.rbとevent.rbに定義したメソッドを用いてよりシンプルに記載しました。

2023-05-11 12:57 UTC, busitora requested changes

2023-05-11 12:57 UTC, busitora commented on app/models/event.rb
> +    self.only_woman == 1
マジックナンバーは  消しましょう!

2023-05-11 12:57 UTC, busitora commented on app/models/user.rb
> +  def not_woman?
woman? メソッドがあるので not_woman? メソッドは woman? の逆なので不要かと!

2023-05-11 12:57 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% if @event.only_woman? and current_user.not_woman?  %>
and ではなく && がよいかと！

2023-05-11 16:09 UTC, nakata59 commented on app/models/event.rb
> +    self.only_woman == 1
44fda9c863db8e2b2a4f17c69917a46c19026bf1
「only_woman?」のカラム方をinteger型からboolean型に変更しマジックナンバーを解消しました。

2023-05-11 16:10 UTC, nakata59 commented on app/models/user.rb
> +  def not_woman?
44fda9c863db8e2b2a4f17c69917a46c19026bf1
not_woman? メソッドを削除しました。

2023-05-11 16:12 UTC, nakata59 commented on app/views/events/show.html.erb
> +                  <% if @event.only_woman? and current_user.not_woman?  %>
44fda9c863db8e2b2a4f17c69917a46c19026bf1
使用する論理演算子を「and」から「&&」に変更しました。

2023-05-14 05:38 UTC, takyyk commented
@nakata59 
LGTMです！

2023-05-20 00:31 UTC, merged